### ISSUE TITLE
volumeMounts not found with helm deployment. 

### ISSUE THREAD

**Issue by zalseryani** [k8tz/k8tz#101]
# Deployment Steps
```bash
helm upgrade --install k8tz k8tz/k8tz \
    --set timezone="Asia/Amman" \
    --set verbose="false" \
    --set injectionStrategy="initContainer" \
    --set injectedInitContainerName="init-k8tz" \
    --set labels.TimeZone="k8tz-managed" \
    --set injectAll="false" \
    --set createNamespace="false" \
    --namespace k8tz
```

# Creating Pod 
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations: 
    k8tz.io/inject: "true"
    k8tz.io/timezone: "Asia/Amman"
    k8tz.io/strategy: "initContainer"
  labels:
    run: ubuntu-test
  name: ubuntu-test
  namespace: test-namespace
spec:
  containers:
  - image: ubuntu:latest
    name: ubuntu-test
    command: 
    - /bin/bash
    - -c
    - sleep infinity
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
```

- When applying this yaml file using kubectl, I get the following error 
```log
The Pod "ubuntu-test" is invalid: 
* spec.containers[0].volumeMounts[1].name: Not found: "k8tz"
* spec.containers[0].volumeMounts[2].name: Not found: "k8tz"
* spec.initContainers[0].volumeMounts[0].name: Not found: "k8tz"
```

- Log of k8tz pod 
```log
INFO: 2024/04/23 09:59:04 admission.go:221: explicit timezone requested on pod's (namespace=test-namespace, name=ubuntu-test) annotation: Asia/Amman
INFO: 2024/04/23 09:59:04 admission.go:230: explicit injection strategy requested on pod's (namespace=test-namespace, name=ubuntu-test) annotation: initContainer
INFO: 2024/04/23 09:59:04 admission.go:313: 9 patches generated for pod (namespace=test-namespace, name=ubuntu-test), timezone=Asia/Amman, strategy=initContainer
```

- Kindly any suggestions ? 

- I tested the cli on the same pod yaml file and tried to apply it on the cluster, it worked fine, but I am not sure if the admission controller is injecting the mutation correctly.
