### ISSUE TITLE
Not Working on Image busybox:1.28

### ISSUE THREAD

**Issue by TienShangHsiu** [k8tz/k8tz#53]
I created a pod on my Kubernetes cluster and I found that k8tz did not work on image - busybox:1.28. If I change the version to busybox:1.34, then it works!!! 

Below is the YAML file I tested. 
```
apiVersion: v1
kind: Pod
metadata:
  name: tz-test
spec:
  containers:
  - name: tz-container
    image: busybox:1.34
    imagePullPolicy: IfNotPresent
    command: [ "/bin/sh" ]
    tty: true
```
