### ISSUE TITLE
SecurityContext for initContainer

### ISSUE THREAD

**Issue by jeroendk** [k8tz/k8tz#57]
Is it somehow possible to define a custom securityContext for the injected initContainer?
We want to enforce a `restricted` admission policy but at the moment we can't due to the initContainers of k8tz.

**Comment by yonatankahana** [comment]
Hi @jeroendk,
I'm considering running k8tz controller and injected initContainers as restricted by default. 
Could you try running a demo version at your cluster and tell me if it solves your problem?

To do that, create `test-restricted-values.yaml` file with contents:

```yaml
# test-restricted-values.yaml
image:
  repository: quay.io/yonatankahana/k8tz
  tag: 0.12.0-beta0

podSecurityContext:
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  runAsNonRoot: true
  seccompProfile:
    type: RuntimeDefault
```

and install/upgrade k8tz:

```console
helm upgrade --install k8tz k8tz/k8tz -f test-restricted-values.yaml
```

Thanks!
