### ISSUE TITLE
Getting 2 volume mount inside POD with  same name "k8tz"

### ISSUE THREAD

**Issue by hari14singh** [k8tz/k8tz#80]
volumeMounts:
    - mountPath: /etc/localtime
      name: k8tz
      readOnly: true
      subPath: Asia/Kolkata
    - mountPath: /usr/share/zoneinfo
      name: k8tz
      readOnly: true

volumes:
  - hostPath:
      path: /usr/share/zoneinfo
      type: ""
    name: k8tz

Getting 2 volume mount inside POD with  same name "k8tz" . This is causing problem. Second 1 is not needed.

[test.txt](https://github.com/k8tz/k8tz/files/12547930/test.txt)

**Comment by yonatankahana** [comment]
Hi @hari14singh,
can you show me the deployment and/or the full pod yaml? I need more information to reproduce the problem

**Comment by brightdroid** [comment]
Same here with current k8tz 0.15.0
Sample pod (trimmed):
```yaml
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8tz.io/injected: "true"
    k8tz.io/timezone: Europe/Berlin
  name: test-nginx-5988dbd68f-s9mqc
  namespace: test
spec:
  containers:
  - env:
    - name: TZ
      value: Europe/Berlin
    image: nginx:1.25.2
    name: nginx
    volumeMounts:
    - mountPath: /etc/localtime
      name: k8tz
      readOnly: true
      subPath: Europe/Berlin
    - mountPath: /usr/share/zoneinfo
      name: k8tz
      readOnly: true
  volumes:
  - hostPath:
      path: /usr/share/zoneinfo
      type: ""
    name: k8tz

```
