### ISSUE TITLE
ignoredNamespaces is not getting values other than "kube-system"

### ISSUE THREAD

**Issue by batulziiy** [k8tz/k8tz#93]
Not sure if other people having the same issue here. But I tried to exclude several namespaces from being k8tz injected. So I tried updating helm release with a new value below : 

```
webhook:
  failurePolicy: Fail

  tlsMinVersion: ""
  tlsCipherSuites: ""

  certManager:
    enabled: false
    secretTemplate: {}
    duration: 2160h
    renewBefore: 720h
    issuerRef:
      name: selfsigned
      kind: ClusterIssuer

  crtPEM: |

  keyPEM: |

  caBundle: |

  ignoredNamespaces:
    - kube-system
    - namespace1
    - namespace2
    - namespace3
    - namespace4
```
After the upgrade, `helm show values` shows only 'kube-system' is ignored and others are not there in 'ignoredNamespace'. 
helm show values k8tz/k8tz :
```
webhook:
  failurePolicy: Fail

  tlsMinVersion: ""
  tlsCipherSuites: ""

  certManager:
    enabled: false
    secretTemplate: {}
    duration: 2160h
    renewBefore: 720h
    issuerRef:
      name: selfsigned
      kind: ClusterIssuer

  crtPEM: |

  keyPEM: |

  caBundle: |

  ignoredNamespaces:
    - kube-system
```
Do you have any suggestion on this? Thanks.
