### ISSUE TITLE
runAsNonRoot needs to be explicitly set for initContainer on restricted namespace

### ISSUE THREAD

**Issue by maitredede** [k8tz/k8tz#98]
Hello,

I am using k8tz 0.16.0. For a namespace [enforcing pod security](https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-namespace-labels/) :

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: yolo
  labels:
    pod-security.kubernetes.io/enforce: restricted
  annotations:
    k8tz.io/strategy: initContainer
```

Pods are not created with error :

```
... violates PodSecurity "restricted:latest": runAsNonRoot != true (pod or container "k8tz" must set securityContext.runAsNonRoot=true)
```
